# Generated by Django 5.2.8 on 2025-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_phoneotp_code_alter_phoneotp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ادمین'), ('customer', 'مشتری'), ('owner', 'صاحب هتل')], default='customer', max_length=8, verbose_name='نقش کاربر'),
        ),
    ]
